{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "CipherTrust IronMail 5.0.1, when \"Denial of Service Protection\" is enabled, allows remote attackers to cause a denial of service (possibly CPU consumption) via a SYN flood with malformed TCP packets from multiple connections."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "407",
                    "url": "http://securityreason.com/securityalert/407"
                },
                {
                    "name": "ironmail-tcpsyn-flood-dos(24445)",
                    "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/24445"
                },
                {
                    "name": "16465",
                    "url": "http://www.securityfocus.com/bid/16465"
                },
                {
                    "name": "1015555",
                    "url": "http://securitytracker.com/id?1015555"
                },
                {
                    "name": "20060203 IronMail-5.0.1-Denial of-Service-Protection-Lets-Remote-Users-Deny-Service",
                    "url": "http://www.securityfocus.com/archive/1/423898/100/0/threaded"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2006-0538",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "CipherTrust IronMail 5.0.1, when \"Denial of Service Protection\" is enabled, allows remote attackers to cause a denial of service (possibly CPU consumption) via a SYN flood with malformed TCP packets from multiple connections."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "407",
                            "refsource": "SREASON",
                            "url": "http://securityreason.com/securityalert/407"
                        },
                        {
                            "name": "ironmail-tcpsyn-flood-dos(24445)",
                            "refsource": "XF",
                            "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/24445"
                        },
                        {
                            "name": "16465",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/16465"
                        },
                        {
                            "name": "1015555",
                            "refsource": "SECTRACK",
                            "url": "http://securitytracker.com/id?1015555"
                        },
                        {
                            "name": "20060203 IronMail-5.0.1-Denial of-Service-Protection-Lets-Remote-Users-Deny-Service",
                            "refsource": "BUGTRAQ",
                            "url": "http://www.securityfocus.com/archive/1/423898/100/0/threaded"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2006-0538",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}