{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "spice-vdagent",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "spice-vdagent versions 0.20 and prior"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A flaw was found in the spice-vdagentd daemon, where it did not properly handle client connections that can be established via the UNIX domain socket in `/run/spice-vdagentd/spice-vdagent-sock`. Any unprivileged local guest user could use this flaw to prevent legitimate agents from connecting to the spice-vdagentd daemon, resulting in a denial of service. The highest threat from this vulnerability is to system availability. This flaw affects spice-vdagent versions 0.20 and prior."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-770",
                            "description": "CWE-770",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-12T00:00:00",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "https://www.openwall.com/lists/oss-security/2020/11/04/1",
                    "url": "https://www.openwall.com/lists/oss-security/2020/11/04/1",
                    "x_refsource": "MISC"
                },
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1886366",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1886366",
                    "x_refsource": "MISC"
                },
                {
                    "name": "[debian-lts-announce] 20210113 [SECURITY] [DLA 2524-1] spice-vdagent security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2021/01/msg00012.html",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "FEDORA-2021-09ce0cdfac",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OIWJ2EIQXWEA2VDBODEATHAT37X4CREP/",
                    "x_refsource": "FEDORA"
                },
                {
                    "name": "FEDORA-2021-510977db25",
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GQT56LATVTB2DJOVVJOKQVMVUXYCT2VB/",
                    "x_refsource": "FEDORA"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2020-25652",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "spice-vdagent",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "spice-vdagent versions 0.20 and prior"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A flaw was found in the spice-vdagentd daemon, where it did not properly handle client connections that can be established via the UNIX domain socket in `/run/spice-vdagentd/spice-vdagent-sock`. Any unprivileged local guest user could use this flaw to prevent legitimate agents from connecting to the spice-vdagentd daemon, resulting in a denial of service. The highest threat from this vulnerability is to system availability. This flaw affects spice-vdagent versions 0.20 and prior."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-770"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://www.openwall.com/lists/oss-security/2020/11/04/1",
                            "refsource": "MISC",
                            "url": "https://www.openwall.com/lists/oss-security/2020/11/04/1"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1886366",
                            "refsource": "MISC",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1886366"
                        },
                        {
                            "name": "[debian-lts-announce] 20210113 [SECURITY] [DLA 2524-1] spice-vdagent security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2021/01/msg00012.html"
                        },
                        {
                            "name": "FEDORA-2021-09ce0cdfac",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/OIWJ2EIQXWEA2VDBODEATHAT37X4CREP/"
                        },
                        {
                            "name": "FEDORA-2021-510977db25",
                            "refsource": "FEDORA",
                            "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GQT56LATVTB2DJOVVJOKQVMVUXYCT2VB/"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2020-25652",
        "dateUpdated": "2022-01-12T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}