{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The HTTP clients in the (1) httplib, (2) urllib, (3) urllib2, and (4) xmlrpclib libraries in CPython (aka Python) 2.x before 2.7.9 and 3.x before 3.4.3, when accessing an HTTPS URL, do not (a) check the certificate against a trust store or verify that the server hostname matches a domain name in the subject's (b) Common Name or (c) subjectAltName field of the X.509 certificate, which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-13T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "RHSA-2017:1162",
                    "url": "https://access.redhat.com/errata/RHSA-2017:1162",
                    "x_refsource": "REDHAT"
                },
                {
                    "name": "https://www.python.org/dev/peps/pep-0476/",
                    "url": "https://www.python.org/dev/peps/pep-0476/",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "71639",
                    "url": "http://www.securityfocus.com/bid/71639",
                    "x_refsource": "BID"
                },
                {
                    "name": "RHSA-2016:1166",
                    "url": "https://access.redhat.com/errata/RHSA-2016:1166",
                    "x_refsource": "REDHAT"
                },
                {
                    "name": "RHSA-2017:1868",
                    "url": "https://access.redhat.com/errata/RHSA-2017:1868",
                    "x_refsource": "REDHAT"
                },
                {
                    "name": "http://bugs.python.org/issue22417",
                    "url": "http://bugs.python.org/issue22417",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "GLSA-201503-10",
                    "url": "https://security.gentoo.org/glsa/201503-10",
                    "x_refsource": "GENTOO"
                },
                {
                    "name": "APPLE-SA-2015-08-13-2",
                    "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html",
                    "x_refsource": "APPLE"
                },
                {
                    "name": "https://www.python.org/downloads/release/python-279/",
                    "url": "https://www.python.org/downloads/release/python-279/",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "http://www.oracle.com/technetwork/topics/security/bulletinjan2015-2370101.html",
                    "url": "http://www.oracle.com/technetwork/topics/security/bulletinjan2015-2370101.html",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "[oss-security] 20141211 CVE request: Python, standard library HTTP clients",
                    "url": "http://www.openwall.com/lists/oss-security/2014/12/11/1",
                    "x_refsource": "MLIST"
                },
                {
                    "name": "https://support.apple.com/kb/HT205031",
                    "url": "https://support.apple.com/kb/HT205031",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html",
                    "url": "http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html",
                    "x_refsource": "CONFIRM"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2014-9365",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The HTTP clients in the (1) httplib, (2) urllib, (3) urllib2, and (4) xmlrpclib libraries in CPython (aka Python) 2.x before 2.7.9 and 3.x before 3.4.3, when accessing an HTTPS URL, do not (a) check the certificate against a trust store or verify that the server hostname matches a domain name in the subject's (b) Common Name or (c) subjectAltName field of the X.509 certificate, which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "RHSA-2017:1162",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:1162"
                        },
                        {
                            "name": "https://www.python.org/dev/peps/pep-0476/",
                            "refsource": "CONFIRM",
                            "url": "https://www.python.org/dev/peps/pep-0476/"
                        },
                        {
                            "name": "71639",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/71639"
                        },
                        {
                            "name": "RHSA-2016:1166",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2016:1166"
                        },
                        {
                            "name": "RHSA-2017:1868",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2017:1868"
                        },
                        {
                            "name": "http://bugs.python.org/issue22417",
                            "refsource": "CONFIRM",
                            "url": "http://bugs.python.org/issue22417"
                        },
                        {
                            "name": "GLSA-201503-10",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/201503-10"
                        },
                        {
                            "name": "APPLE-SA-2015-08-13-2",
                            "refsource": "APPLE",
                            "url": "http://lists.apple.com/archives/security-announce/2015/Aug/msg00001.html"
                        },
                        {
                            "name": "https://www.python.org/downloads/release/python-279/",
                            "refsource": "CONFIRM",
                            "url": "https://www.python.org/downloads/release/python-279/"
                        },
                        {
                            "name": "http://www.oracle.com/technetwork/topics/security/bulletinjan2015-2370101.html",
                            "refsource": "CONFIRM",
                            "url": "http://www.oracle.com/technetwork/topics/security/bulletinjan2015-2370101.html"
                        },
                        {
                            "name": "[oss-security] 20141211 CVE request: Python, standard library HTTP clients",
                            "refsource": "MLIST",
                            "url": "http://www.openwall.com/lists/oss-security/2014/12/11/1"
                        },
                        {
                            "name": "https://support.apple.com/kb/HT205031",
                            "refsource": "CONFIRM",
                            "url": "https://support.apple.com/kb/HT205031"
                        },
                        {
                            "name": "http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html",
                            "refsource": "CONFIRM",
                            "url": "http://www.oracle.com/technetwork/topics/security/bulletinoct2015-2511968.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2014-9365",
        "dateUpdated": "2022-01-13T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}