{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "rsyslog:",
                    "vendor": "The rsyslog Project",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "8.27.0",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A denial of service vulnerability was found in rsyslog in the imptcp module. An attacker could send a specially crafted message to the imptcp socket, which would cause rsyslog to crash. Versions before 8.27.0 are vulnerable."
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "vectorString": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                        "version": "3.0"
                    }
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-190",
                            "description": "CWE-190",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "RHSA-2019:2110",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2110"
                },
                {
                    "name": "RHSA-2019:2439",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2439"
                },
                {
                    "name": "RHSA-2019:2437",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2437"
                },
                {
                    "name": "RHBA-2019:2501",
                    "url": "https://access.redhat.com/errata/RHBA-2019:2501"
                },
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16881",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16881"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2018-16881",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "rsyslog:",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "8.27.0"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "The rsyslog Project"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A denial of service vulnerability was found in rsyslog in the imptcp module. An attacker could send a specially crafted message to the imptcp socket, which would cause rsyslog to crash. Versions before 8.27.0 are vulnerable."
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-190"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "RHSA-2019:2110",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2110"
                        },
                        {
                            "name": "RHSA-2019:2439",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2439"
                        },
                        {
                            "name": "RHSA-2019:2437",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2437"
                        },
                        {
                            "name": "RHBA-2019:2501",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHBA-2019:2501"
                        },
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16881",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16881"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2018-16881",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}