{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "undertow",
                    "vendor": "Red Hat",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "2.0.21",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A vulnerability was found in Undertow web server before 2.0.21. An information exposure of plain text credentials through log files because Connectors.executeRootHandler:402 logs the HttpServerExchange object at ERROR level using UndertowLogger.REQUEST_LOGGER.undertowRequestFailed(t, exchange)"
                }
            ],
            "metrics": [
                {
                    "cvssV3_0": {
                        "vectorString": "5.3/CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
                        "version": "3.0"
                    }
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "cweId": "CWE-532",
                            "description": "CWE-532",
                            "lang": "en",
                            "type": "CWE"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
                "shortName": "redhat"
            },
            "references": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3888",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3888"
                },
                {
                    "name": "108739",
                    "url": "http://www.securityfocus.com/bid/108739"
                },
                {
                    "name": "RHSA-2019:2439",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2439"
                },
                {
                    "name": "RHSA-2019:2998",
                    "url": "https://access.redhat.com/errata/RHSA-2019:2998"
                },
                {
                    "name": "RHSA-2020:0727",
                    "url": "https://access.redhat.com/errata/RHSA-2020:0727"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "secalert@redhat.com",
                    "ID": "CVE-2019-3888",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "undertow",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "2.0.21"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "Red Hat"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A vulnerability was found in Undertow web server before 2.0.21. An information exposure of plain text credentials through log files because Connectors.executeRootHandler:402 logs the HttpServerExchange object at ERROR level using UndertowLogger.REQUEST_LOGGER.undertowRequestFailed(t, exchange)"
                        }
                    ]
                },
                "impact": {
                    "cvss": [
                        [
                            {
                                "vectorString": "5.3/CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
                                "version": "3.0"
                            }
                        ]
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "CWE-532"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3888",
                            "refsource": "CONFIRM",
                            "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3888"
                        },
                        {
                            "name": "108739",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/108739"
                        },
                        {
                            "name": "RHSA-2019:2439",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2439"
                        },
                        {
                            "name": "RHSA-2019:2998",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2019:2998"
                        },
                        {
                            "name": "RHSA-2020:0727",
                            "refsource": "REDHAT",
                            "url": "https://access.redhat.com/errata/RHSA-2020:0727"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "53f830b8-0a3f-465b-8143-3b8a9948e749",
        "assignerShortName": "redhat",
        "cveId": "CVE-2019-3888",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}