{
    "containers": {
        "cna": {
            "affected": [
                {
                    "defaultStatus": "unknown",
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "Pillow before 3.3.2 allows context-dependent attackers to obtain sensitive information by using the \"crafted image file\" approach, related to an \"Integer Overflow\" issue affecting the Image.core.map_buffer in map.c component."
                }
            ],
            "problemTypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2022-01-12T00:00:00",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f",
                    "url": "https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "GLSA-201612-52",
                    "url": "https://security.gentoo.org/glsa/201612-52",
                    "x_refsource": "GENTOO"
                },
                {
                    "name": "94234",
                    "url": "http://www.securityfocus.com/bid/94234",
                    "x_refsource": "BID"
                },
                {
                    "name": "https://github.com/python-pillow/Pillow/issues/2105",
                    "url": "https://github.com/python-pillow/Pillow/issues/2105",
                    "x_refsource": "CONFIRM"
                },
                {
                    "name": "DSA-3710",
                    "url": "http://www.debian.org/security/2016/dsa-3710",
                    "x_refsource": "DEBIAN"
                },
                {
                    "name": "http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html",
                    "url": "http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html",
                    "x_refsource": "CONFIRM"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2016-9189",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "Pillow before 3.3.2 allows context-dependent attackers to obtain sensitive information by using the \"crafted image file\" approach, related to an \"Integer Overflow\" issue affecting the Image.core.map_buffer in map.c component."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/python-pillow/Pillow/pull/2146/commits/c50ebe6459a131a1ea8ca531f10da616d3ceaa0f"
                        },
                        {
                            "name": "GLSA-201612-52",
                            "refsource": "GENTOO",
                            "url": "https://security.gentoo.org/glsa/201612-52"
                        },
                        {
                            "name": "94234",
                            "refsource": "BID",
                            "url": "http://www.securityfocus.com/bid/94234"
                        },
                        {
                            "name": "https://github.com/python-pillow/Pillow/issues/2105",
                            "refsource": "CONFIRM",
                            "url": "https://github.com/python-pillow/Pillow/issues/2105"
                        },
                        {
                            "name": "DSA-3710",
                            "refsource": "DEBIAN",
                            "url": "http://www.debian.org/security/2016/dsa-3710"
                        },
                        {
                            "name": "http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html",
                            "refsource": "CONFIRM",
                            "url": "http://pillow.readthedocs.io/en/3.4.x/releasenotes/3.3.2.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2016-9189",
        "dateUpdated": "2022-01-12T00:00:00",
        "state": "PUBLISHED"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}