{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "Xiaomi router AX3600",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "rom version =1.0.50",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "A RACE CONDITION on XQBACKUP causes a decompression path error on Xiaomi router AX3600 with ROM version =1.0.50."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "Remote code execution",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "b57733aa-7326-4f07-8e09-0be8e0df1909",
                "shortName": "Xiaomi"
            },
            "references": [
                {
                    "name": "https://privacy.mi.com/trust#/security/vulnerability-management/vulnerability-announcement/detail?id=26&locale=zh",
                    "url": "https://privacy.mi.com/trust#/security/vulnerability-management/vulnerability-announcement/detail?id=26&locale=zh"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "security@xiaomi.com",
                    "ID": "CVE-2020-14104",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "Xiaomi router AX3600",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "rom version =1.0.50"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "A RACE CONDITION on XQBACKUP causes a decompression path error on Xiaomi router AX3600 with ROM version =1.0.50."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "Remote code execution"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://privacy.mi.com/trust#/security/vulnerability-management/vulnerability-announcement/detail?id=26&locale=zh",
                            "refsource": "MISC",
                            "url": "https://privacy.mi.com/trust#/security/vulnerability-management/vulnerability-announcement/detail?id=26&locale=zh"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "b57733aa-7326-4f07-8e09-0be8e0df1909",
        "assignerShortName": "Xiaomi",
        "cveId": "CVE-2020-14104",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}