{
    "containers": {
        "cna": {
            "affected": [
                {
                    "product": "n/a",
                    "vendor": "n/a",
                    "versions": [
                        {
                            "status": "affected",
                            "version": "n/a",
                            "versionType": "custom"
                        }
                    ]
                }
            ],
            "descriptions": [
                {
                    "lang": "en",
                    "value": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py."
                }
            ],
            "problemtypes": [
                {
                    "descriptions": [
                        {
                            "description": "n/a",
                            "lang": "en",
                            "type": "text"
                        }
                    ]
                }
            ],
            "providerMetadata": {
                "dateUpdated": "2021-12-15",
                "orgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
                "shortName": "mitre"
            },
            "references": [
                {
                    "name": "https://github.com/pypa/pip/issues/6413",
                    "url": "https://github.com/pypa/pip/issues/6413"
                },
                {
                    "name": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace",
                    "url": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace"
                },
                {
                    "name": "https://github.com/pypa/pip/compare/19.1.1...19.2",
                    "url": "https://github.com/pypa/pip/compare/19.1.1...19.2"
                },
                {
                    "name": "[debian-lts-announce] 20200911 [SECURITY] [DLA 2370-1] python-pip security update",
                    "url": "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html"
                },
                {
                    "name": "openSUSE-SU-2020:1598",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html"
                },
                {
                    "name": "openSUSE-SU-2020:1613",
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html"
                }
            ],
            "x_legacyV4Record": {
                "CVE_data_meta": {
                    "ASSIGNER": "cve@mitre.org",
                    "ID": "CVE-2019-20916",
                    "STATE": "PUBLIC"
                },
                "affects": {
                    "vendor": {
                        "vendor_data": [
                            {
                                "product": {
                                    "product_data": [
                                        {
                                            "product_name": "n/a",
                                            "version": {
                                                "version_data": [
                                                    {
                                                        "version_value": "n/a"
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                "vendor_name": "n/a"
                            }
                        ]
                    }
                },
                "data_format": "MITRE",
                "data_type": "CVE",
                "data_version": "4.0",
                "description": {
                    "description_data": [
                        {
                            "lang": "eng",
                            "value": "The pip package before 19.2 for Python allows Directory Traversal when a URL is given in an install command, because a Content-Disposition header can have ../ in a filename, as demonstrated by overwriting the /root/.ssh/authorized_keys file. This occurs in _download_http_url in _internal/download.py."
                        }
                    ]
                },
                "problemtype": {
                    "problemtype_data": [
                        {
                            "description": [
                                {
                                    "lang": "eng",
                                    "value": "n/a"
                                }
                            ]
                        }
                    ]
                },
                "references": {
                    "reference_data": [
                        {
                            "name": "https://github.com/pypa/pip/issues/6413",
                            "refsource": "MISC",
                            "url": "https://github.com/pypa/pip/issues/6413"
                        },
                        {
                            "name": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace",
                            "refsource": "MISC",
                            "url": "https://github.com/gzpan123/pip/commit/a4c735b14a62f9cb864533808ac63936704f2ace"
                        },
                        {
                            "name": "https://github.com/pypa/pip/compare/19.1.1...19.2",
                            "refsource": "MISC",
                            "url": "https://github.com/pypa/pip/compare/19.1.1...19.2"
                        },
                        {
                            "name": "[debian-lts-announce] 20200911 [SECURITY] [DLA 2370-1] python-pip security update",
                            "refsource": "MLIST",
                            "url": "https://lists.debian.org/debian-lts-announce/2020/09/msg00010.html"
                        },
                        {
                            "name": "openSUSE-SU-2020:1598",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00005.html"
                        },
                        {
                            "name": "openSUSE-SU-2020:1613",
                            "refsource": "SUSE",
                            "url": "http://lists.opensuse.org/opensuse-security-announce/2020-10/msg00010.html"
                        }
                    ]
                }
            }
        }
    },
    "cveMetadata": {
        "assignerOrgId": "8254265b-2729-46b6-b9e3-3dfca2d5bfca",
        "assignerShortName": "mitre",
        "cveId": "CVE-2019-20916",
        "dateUpdated": "2021-12-15",
        "state": "PUBLIC"
    },
    "dataType": "CVE_RECORD",
    "dataVersion": "5.0"
}